language: python
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "3.5"
before_install:
  - pip install nose coverage
script:
  # Note: nose has to be run with nocapture to avoid the
  # _io.StringIO object has no attribute "buffer" error
  - nosetests --nocapture -v --with-coverage --cover-inclusive --cover-package=kqml
